# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e7920d5c7dd368a69c19a0465b3fb330f4f267658b8011a87ed92988b48cbb5a44cd86abc221a385293297b93e3b34212bfdba50b0c7c78f27f93427f1ac9d7

test:
  secret_key_base: 83a5b6a71d3273b7177778757b2024f49d9c12b23ea38918cb32c5a0be59b75ef87d947ee084bfe34af1c1f7c0b0829e88bd53371f2a6349da6da1a4a3cb6dbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
